# Tap
tap "homebrew/cask-versions"
tap "homebrew/cask-fonts"

# Core
brew "git"
brew "tig"
brew "zsh"
brew "zsh-autosuggestions"
brew "zsh-completions"
brew "zsh-syntax-highlighting"
brew "grep"
brew "jq"
brew "curl"
brew "wget"
brew "nvm"
brew "cask"
brew "go"
brew "coreutils"
brew "findutils"
brew "thefuck" # CLI failed command correction
brew "ncdu" # Interactive diskspace overview
brew "ffmpeg"
brew "gifsicle"
brew "tldr"
brew "svn" # Needed for fonts
brew "cmake"

# Cask
cask "1password"
cask "spectacle"
cask "visual-studio-code"
cask "tableplus"
cask "docker"
cask "google-chrome"
cask "spotify"
cask "slack"
cask "discord"
cask "font-open-sans"
cask "font-roboto"
cask "font-source-code-pro"
cask "font-roboto-mono-for-powerline"
cask "font-hack"
cask "hyper"
cask "viscosity"
cask "brooklyn"
